### ISSUE TITLE
Assets files are not refreshed after updating

### ISSUE THREAD

**Issue by fae7em** [humhub/humhub-modules-updater#21]
### What steps will reproduce the problem?
If in a new version of humhub, there are some changes in assets files, the assets directory are not re-published and use the old assets files.

like https://github.com/humhub/humhub/issues/4605 issue, that new feature is not working because of assets cache.

Updater should clean the assets directory, to force Yii to re-publish assets files.

**Comment by buddh4** [comment]
@luke- do you think this is a problem regarding performance since Flushing assets take some time. Also currently active user will have to reload the page in order for new assets to be updated. Maybe related to https://github.com/humhub/humhub/issues/4514

**Comment by fae7em** [comment]
We can put it in the `CleanUp` step to run just one time and at the end of the updating process. 

https://github.com/humhub/humhub-modules-updater/blob/2ef8d88aa6f0d87e4a43ad0c1899cdb25bd058bb/modules/packageinstaller/controllers/InstallController.php#L87-L96

**Comment by luke-** [comment]
Yes, as very last step would be the safest way.
