### ISSUE TITLE
Show current update channel with link to module configuration more visible. 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-updater#24]
![image](https://user-images.githubusercontent.com/4736168/107019479-00c1dd00-67a2-11eb-9666-ba605ff93e29.png)

**Comment by luke-** [comment]
Another small issue:

![image](https://user-images.githubusercontent.com/4736168/107022079-3e743500-67a5-11eb-9827-9de3c8b1250b.png)

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub-modules-updater/pull/25

<img width="858" alt="current_update_version" src="https://user-images.githubusercontent.com/6995524/107036200-48f4f580-67ca-11eb-80d0-51be2406b6aa.png">

> Another small issue:

I changed the url to `/marketplace/update`.
