### ISSUE TITLE
Updater is available for installation in HumHub > Admin > Modules on v0.11.2, but min version is 0.20

### ISSUE THREAD

**Issue by dakur** [humhub/humhub-modules-updater#7]
...so when user tries to install this module on v0.11.2, it returns "ZipArchive::extractTo(/.../humhub/protected/modules/updater/views/update): failed to open stream: Is a directory".
I guess it should not display on Modules page in this version of HumHub.

**Comment by luke-** [comment]
There is no automatic update available between 0.11 and 0.20.
